// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-mUgq7GXx_4JKSgV53U9lBeRXrYm9NN8',
    appId: '1:912544443039:web:c8186bbc575911900a90aa',
    messagingSenderId: '912544443039',
    projectId: 'ecommerce-mallshop',
    authDomain: 'ecommerce-mallshop.firebaseapp.com',
    storageBucket: 'ecommerce-mallshop.appspot.com',
    measurementId: 'G-MVXV9CETMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgp2RVthjNvWVLCv3JB1WP3aFV93n9KPg',
    appId: '1:912544443039:android:bf2fd2355e8785860a90aa',
    messagingSenderId: '912544443039',
    projectId: 'ecommerce-mallshop',
    storageBucket: 'ecommerce-mallshop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCx5eyNRAvRIcsOo8ScVrYFkN73K9eipI',
    appId: '1:912544443039:ios:f0d33cf8159f7c480a90aa',
    messagingSenderId: '912544443039',
    projectId: 'ecommerce-mallshop',
    storageBucket: 'ecommerce-mallshop.appspot.com',
    iosBundleId: 'com.example.mallshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCx5eyNRAvRIcsOo8ScVrYFkN73K9eipI',
    appId: '1:912544443039:ios:f0d33cf8159f7c480a90aa',
    messagingSenderId: '912544443039',
    projectId: 'ecommerce-mallshop',
    storageBucket: 'ecommerce-mallshop.appspot.com',
    iosBundleId: 'com.example.mallshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-mUgq7GXx_4JKSgV53U9lBeRXrYm9NN8',
    appId: '1:912544443039:web:f5d3f9de9fb695670a90aa',
    messagingSenderId: '912544443039',
    projectId: 'ecommerce-mallshop',
    authDomain: 'ecommerce-mallshop.firebaseapp.com',
    storageBucket: 'ecommerce-mallshop.appspot.com',
    measurementId: 'G-QRYTVRGGPD',
  );
}
